<a href="https://colab.research.google.com/github/wojsamjan/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy Intro**

In [2]:
import numpy as np
np.__version__

'1.25.2'

**1D Array**

In [8]:
x = np.array([1, 2])
x

array([1, 2])

In [10]:
type(x)

numpy.ndarray

In [13]:
np.ndim(x)

1

In [15]:
np.shape(x)

(2,)

In [17]:
np.size(x)

2

In [19]:
x.dtype

dtype('int64')

**2D Array**

In [21]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
type(x)

numpy.ndarray

In [24]:
np.ndim(x)

2

In [25]:
np.shape(x)

(2, 3)

In [26]:
np.size(x)

6

In [27]:
np.size(x, axis=0)

2

In [29]:
np.size(x, axis=1)

3

In [30]:
x.dtype

dtype('int64')

**3D Array**

In [51]:
x = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],
    [
        [9, 10, 11, 12],
        [13, 14, 15, 16]
    ],
    [
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [52]:
np.ndim(x)

3

In [53]:
np.shape(x)

(3, 2, 4)

In [54]:
np.size(x)

24

In [55]:
np.size(x, axis=0)

3

In [56]:
np.size(x, axis=1)

2

In [57]:
np.size(x, axis=2)

4

**Data Types**

In [72]:
x = np.array([1, 2, 3])
x.dtype

dtype('int64')

In [73]:
x

array([1, 2, 3])

In [76]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [77]:
x

array([1., 2., 3.])

In [78]:
x = np.array([1, 2, 3], dtype='float')
x.dtype

dtype('float64')

In [79]:
x

array([1., 2., 3.])

In [80]:
x = np.array([1.7, 2.7, 3.7], dtype='int')
x.dtype

dtype('int64')

In [81]:
x

array([1, 2, 3])

In [82]:
x = np.array([1, 2, 3], dtype='complex')
x.dtype

dtype('complex128')

In [83]:
x

array([1.+0.j, 2.+0.j, 3.+0.j])

In [85]:
x = np.array([True, False])
x.dtype

dtype('bool')

In [86]:
x

array([ True, False])

**Creating Arrays**

In [88]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
np.ones(shape=(3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.full(shape=(3, 3), fill_value=7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [94]:
np.full(shape=(3, 3), fill_value=7, dtype='float')

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [98]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [102]:
np.arange(start=10, stop=20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [105]:
np.arange(start=10, stop=20, step=2)

array([10, 12, 14, 16, 18])

In [108]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [109]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

**Reshaping Arrays**

In [111]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [113]:
np.arange(15).reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
np.arange(15).reshape(-1, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Basic Operations on Arrays**

In [125]:
a = np.array([1, 2, 3, 4])
b = np.array([1, -2, 1, 2])
print(a)
print(b)

[1 2 3 4]
[ 1 -2  1  2]


In [126]:
a + b

array([2, 0, 4, 6])

In [130]:
np.add(a, b)

array([2, 0, 4, 6])

In [127]:
a - b

array([0, 4, 2, 2])

In [131]:
np.subtract(a, b)

array([0, 4, 2, 2])

In [128]:
a * b

array([ 1, -4,  3,  8])

In [132]:
np.multiply(a, b)

array([ 1, -4,  3,  8])

In [129]:
a / b

array([ 1., -1.,  3.,  2.])

In [134]:
np.divide(a, b)

array([ 1., -1.,  3.,  2.])

In [140]:
print(a)
print(b)

[1 2 3 4]
[ 1 -2  1  2]


In [139]:
a + 2

array([3, 4, 5, 6])

In [137]:
a + 2*b

array([ 3, -2,  5,  8])

In [147]:
x = np.array([
    [1, 3],
    [2, 4]
])
y = np.array([
    [-1, 2],
    [3, 0]
])
print(x, '\n')
print(y)

[[1 3]
 [2 4]] 

[[-1  2]
 [ 3  0]]


In [149]:
x * y

array([[-1,  6],
       [ 6,  0]])

In [154]:
np.dot(x, y)
# x.dot(y)
# x @ y
# y @ x

array([[ 8,  2],
       [10,  4]])

**Indexing & Slicing Arrays**

In [158]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
a[1]

2

In [163]:
a[[0, 2]]

array([1, 3])

In [165]:
a[5:]

array([6, 7, 8, 9])

In [170]:
a = a.reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
a[0]

array([1, 2, 3])

In [173]:
a[:, 0]

array([1, 4, 7])

In [175]:
a[1, 1]

5

In [178]:
# a[1:3, 0:2]
a[1:, :2]

array([[4, 5],
       [7, 8]])